services:

  postgres:
    container_name: appointment-system-db
    image: postgres:18-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appointment_system

  backend:
    container_name: appoinment-system-api
    build: ./backend
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:password@db:5432/appointment_system

volumes:
  postgres-data: